apiVersion: v1  # 不要改动
kind: Plugin  # 不要改动
metadata:
  # author 和 name 唯一确定一个插件
  author: HwlloChen  # 插件作者，修改为你的名称
  name: SendLike  # 插件名称，修改为你的插件名称
  repository: 'https://github.com/HwlloChen/SendLike'  # 插件仓库地址，修改为你的插件 GitHub 仓库地址
  version: 0.1.2  # 插件版本，修改为你的插件版本
  description:  # 插件简介，修改为你的插件简介，支持多语言
    en_US: Plugin for sending likes
    zh_CN: 发送点赞
  label:  # 插件显示名称，支持多语言。在 WebUI 上会显示对应语言的 label
    en_US: Send Like
    zh_CN: Send Like
spec:
  # 插件配置（可选），可配置多项
  config:
    - name: api  # OneBot API 地址
      label:  # 配置项显示名称，支持多语言
      en_US: OneBot API Address
      zh_CN: OneBot API 地址
      description:  # 配置项描述，支持多语言
      en_US: The OneBot API address for sending messages
      zh_CN: 用于发送消息的 OneBot API 地址
      type: string  # 配置项类型，支持 string, integer, float, boolean 等
      default: 'http://127.0.0.1:3000'  # 配置项默认值
      required: true  # 配置项是否必填
execution:
  python:
    path: main.py  # 插件主程序路径，必须与上方插件入口代码的文件名相同
    attr: SendLike  # 插件类名，必须与上方代码中声明的类名相同
